### ISSUE TITLE
Add attribute to configure root url (e.g. for Frontend-Backend-Infrastructures)

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/sensor-things#20]
Examples are in Eventing / SOS
@CarstenHollmann knows

**Comment by SpeckiJ** [comment]
This is implemented in https://github.com/52North/sensor-things/commit/591c9845dc5ea10144f940ad383ad41650bc010d for http and https://github.com/52North/sensor-things/commit/f66a929602c30c4498be2e55745e60245c5a9d16 for mqtt.
