### ISSUE TITLE
Licensing.

### ISSUE THREAD

**Issue by SpeckiJ** [52North/sensor-things#7]
Wir haben momentan im Projekt eine enorme Breite an Lizenzinformationen:

- im root ist als LICENSE die GnuGPLv3 hinterlegt
- in einigen .java files steht die 52North GPLv2 2019 [siehe hier](https://github.com/52North/sensor-things/blob/26d7e0ea4cb384f780cd08550324fa714bcb94a7/sensor-things-api-core/src/main/java/org/n52/sta/data/query/DatastreamQuerySpecifications.java#L1)
- in einigen .java files steht gar nix
- in einigen .java files steht der Default Header von Netbeans [siehe hier](https://github.com/52North/sensor-things/blob/018b0f573728d04999cb3a2cf2413178c89599f8/sensor-things-api-mqtt/src/main/java/org/n52/sta/mqtt/handler/MqttEntityCollectionSubscriptionHandler.java#L2)
- in einigen .java files steht die 52North GPLv2 2018 

Das muss vor einem Release auf jeden Fall gerade gezogen werden!

**Comment by CarstenHollmann** [comment]
Dafür sollte einen oder _etc_ Ordner mit dem License-Text erstellt werden, z.B. wie beim SOS (https://github.com/52North/SOS/blob/develop/misc/52N_license.txt) order arctic sea (https://github.com/52North/arctic-sea/blob/master/etc/license-header.txt)

Dann folgende plugins defiunieren:

```
<plugin>
	<groupId>org.codehaus.gmaven</groupId>
	<artifactId>groovy-maven-plugin</artifactId>
	<executions>
		<execution>
			<phase>initialize</phase>
			<goals>
				<goal>execute</goal>
			</goals>
			<configuration>
				<source>project.properties['currentYear'] = java.time.Year.now().toString()</source>
			</configuration>
		</execution>
	</executions>
</plugin>
```

```
<plugin>
	<groupId>com.mycila</groupId>
	<artifactId>license-maven-plugin</artifactId>
	<inherited>false</inherited>
	<configuration>
		<aggregate>true</aggregate>
		<header>etc/license-header.txt</header>
		<includes>
			<include>**/*.java</include>
			<include>**/*.xml</include>
		</includes>
		<strictCheck>true</strictCheck>
		<properties>
			<year>${project.inceptionYear}-${currentYear}</year>
		</properties>
		<mapping>
			<java>SLASHSTAR_STYLE</java>
		</mapping>
	</configuration>
	<executions>
		<execution>
			<id>format-license-headers</id>
			<phase>process-resources</phase>
			<goals>
				<goal>format</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Und dann mit `license:format` bauen. Dann werden alle Header in den Files mit dem definierten Header ersetzt.

**Comment by SpeckiJ** [comment]
this is fixed now
