### ISSUE TITLE
Redundant MQTT message publishing

### ISSUE THREAD

**Issue by SebaDro** [52North/sensor-things#9]
The creation of new entities which links to other existing entities results in multiple events for the [`HibernateMessageInterceptor`](
        sensor-things/sensor-things-api-core/src/main/java/org/n52/sta/HibernateMessageInterceptor.java
      ). Following an example post body for creating a new _Things_ Entity that will be posted against _./sta/Things_:
```
{
        "description": "thing 1",
	"name": "thing name 1",
	"properties": {
		"reference": "first"
	},
	"Locations": [{ 
    	     "@iot.id": 1 
        }]
}
```
Such a post results in four different events:
* `onSave` for _ThingEntity_
* `onSave` for _HistoricalLocationEntity_
* `onFlushDirty` for _ThingEntity_
* `onFlushDirty` for _LocationEntity_  

As a result, a client that has subscribed for the topic `/Locations(1)/Things` would receive two messages, each for the two events for the _ThingsEntity_ that will be handled seperately by the _MqttEventHandler_.

**Comment by SpeckiJ** [comment]
MQTT Subscription handling has been completely refactored in 35c4ecf9a2ce77200c8c1a0d6dcc87558fba4fc1.

Additionally the Repositories now support a separate save-Method skipping mqtt handling as of a4c7c4853b19c727118c6fdea5700ef1fd56b055. This method should be used when saving entities multiple times during creation and prevent double-sending of mqtt messages.
